[project]
name = 'token-streaming-protocol'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'

[contracts]
stream = "contracts/stream.clar"
