[project]
name = "token-streaming-protocol"
description = "A token streaming protocol for time-based payments"
authors = []
telemetry = false
cache_dir = "./.clarinet"

[contracts.stream]
path = "contracts/stream.clar"
clarity_version = 2
epoch = 2.1

[repl.analysis]
passes = ["check_checker"]

[[repl.analysis.check_checker.switches]]
diagnostics = true
impure = true
style = "clarity2"

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 1_000_000_000_000

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 1_000_000_000_000

[accounts.wallet_2] 
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital"
balance = 1_000_000_000_000

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high"
balance = 1_000_000_000_000

[devnet]
disable_bitcoin_explorer = true
# bitcoin_node_p2p_port = 18444
# bitcoin_node_rpc_port = 18443
# bitcoin_controller_port = 18442
disable_stacks_explorer = true
disable_stacks_api = true
# stacks_node_rpc_port = 20443
# stacks_node_p2p_port = 20444
# stacks_api_port = 3999
# stacks_api_events_port = 3700
# bitcoin_controller_block_time = 30_000
pox_stacking_orders = []

[testnet]
stacks_node_rpc_port = 20443
# bitcoin_node_p2p_port = 18444
# bitcoin_node_rpc_port = 18443
# bitcoin_controller_port = 18442